---
driver:
  name: vagrant
  customize:
    memory: 1024
    cpuexecutioncap: 50
  synced_folders:
    - ["<%= File.expand_path(File.dirname(__FILE__)) %>/plugins", "/opt/ohai-plugins"]
    - ["<%= File.expand_path("..", __FILE__) %>", "/home/vagrant/<%= File.basename(File.expand_path("..", __FILE__)) %>"]
driver_config:
  require_chef_omnibus: latest
provisioner:
  name: chef_solo
platforms:
  - name: ubuntu-10.04
    driver_config:
      box: vagrant-ubuntu-10.04
      box_url: http://files.vagrantup.com/lucid64.box
      require_chef_omnibus: true
    run_list:
    - recipe[omnibus_ohai_solo::apt]
    - recipe[apt]
  - name: ubuntu-12.04
    driver_config:
      box: vagrant-ubuntu-12.04
      box_url: http://files.vagrantup.com/precise64.box
      require_chef_omnibus: true
    run_list:
    - recipe[omnibus_ohai_solo::apt]
    - recipe[apt]
  - name: ubuntu-12.10
    driver_config:
      box: vagrant-ubuntu-12.10
      box_url: http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_ubuntu-12.10_chef-provisionerless.box
      require_chef_omnibus: true
    run_list:
    - recipe[omnibus_ohai_solo::apt]
    - recipe[apt]
  - name: ubuntu-13.04
    driver_config:
      box: vagrant-ubtuntu-13.04
      box_url: http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_ubuntu-13.04_chef-provisionerless.box
      require_chef_omnibus: true
    run_list:
    - recipe[omnibus_ohai_solo::apt]
    - recipe[apt]
  - name: ubuntu-13.10
    driver_config:
      box: vagrant-ubuntu-13.10
      box_url: http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_ubuntu-13.10_chef-provisionerless.box
      require_chef_omnibus: true
    run_list:
    - recipe[omnibus_ohai_solo::apt]
    - recipe[apt]
# Ubuntu 14.04's version of readline is imcompatible with compiling Ruby.
# Fix provided in https://bugs.ruby-lang.org/issues/9578 but will not
# ship until Ruby 2.1.2.
#  - name: ubuntu-14.04
#    driver_config:
#      box: vagrant-ubuntu-14.04
#      box_url: http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_ubuntu-14.04_chef-provisionerless.box
#      require_chef_omnibus: true
#    run_list:
#    - recipe[apt]
  - name: centos-5
    driver_config:
      box: vagrant-centos-5
      box_url: http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_centos-5.10_chef-provisionerless.box
      require_chef_omnibus: true
  - name: centos-6
    driver_config:
      box: vagrant-centos-6
      box_url: http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_centos-6.5_chef-provisionerless.box
      require_chef_omnibus: true
  - name: debian-6
    driver_config:
      box: vagrant-debian-6
      box_url: http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_debian-6.0.8_chef-provisionerless.box
      require_chef_omnibus: true
    run_list:
    - recipe[omnibus_ohai_solo::apt]
    - recipe[apt]
  - name: debian-7
    driver_config:
      box: vagrant-debian-7
      box_url: http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_debian-7.2.0_chef-provisionerless.box
      require_chef_omnibus: true
    run_list:
    - recipe[omnibus_ohai_solo::apt]
    - recipe[apt]

suites:
- name: ohai-solo
  run_list:
    - recipe[build-essential]
    - recipe[git::source]
    - recipe[omnibus::default]
    - recipe[omnibus_ohai_solo::default]
    - recipe[omnibus_ohai_solo::upload]
  attributes:
    apt:
      compile_time_update: true
    build-essential:
      compile_time: true
    git:
      version: "1.9.0"
    omnibus:
      ruby_version: "1.9.3-p484"
    omnibus_ohai_solo:
      rs_username: <%= ENV['RS_USERNAME'] %>
      rs_apikey: <%= ENV['RS_APIKEY'] %>
      rs_region: <%= ENV['RS_CONTAINER_REGION'] %>
      rs_container: <%= ENV['RS_CONTAINER'] %>
      release_environment: <%= ENV['OHAI_RELEASE_ENV'] %>
      ref: <%= ENV['OHAI_SOLO_VERSION'] || "HEAD" %>
      build_version: <%= ENV['OHAI_SOLO_VERSION'] %>
      append_timestamp: <%= ENV['APPEND_TIMESTAMP'] || "true" %>
    ohai_plugins:
      ref: <%= ENV['OHAI_PLUGINS_VERSION'] || "HEAD" %>
    rackspacecloud:
      fog_version: "1.22.0"
    xml:
      nokogiri:
        version: "1.6.1"
