---
driver_plugin: rackspace
driver_config:
  require_chef_omnibus: latest
  rackspace_username: <%= ENV['RS_USERNAME'] %>
  rackspace_api_key: <%= ENV['RS_APIKEY'] %>
  test_base_path: /opt/build
  public_key_path: <%= ENV['SSH_KEY_FILE'] %>
  flavor_id: <%= ENV['RS_FLAVOR'] %>
  rackspace_region: <%= ENV['RS_REGION'] %>

platforms:
- name: ubuntu-1304
  driver_config:
    image_id: 4b54f5a0-137f-4751-8e7c-fe707185e531
  run_list:
  - recipe[apt]
- name: ubuntu-1210
  driver_config:
    image_id: 3dfff025-724f-44d9-af75-f94e7f09eae6
  run_list:
  - recipe[apt]
- name: ubuntu-1204
  driver_config:
    image_id: c9c7732f-5129-4930-a835-3781255fb1e2
  run_list:
  - recipe[apt]
- name: ubuntu-1110
  driver_config:
    image_id: 3afe97b2-26dc-49c5-a2cc-a2fc8d80c001
  run_list:
  - recipe[apt]
- name: ubuntu-1004
  driver_config:
    image_id: aab63bcf-89aa-440f-b0c7-c7a1c611914b
  run_list:
  - recipe[apt]
- name: debian-6
  driver_config:
    image_id: 695ca76e-fc0d-4e36-82e0-8ed66480a999
  run_list:
  - recipe[apt]
- name: debian-7
  driver_config:
    image_id: 11dfbc2f-90f5-45f8-8162-f49524096ca4
  run_list:
  - recipe[apt]
- name: centos-6
  driver_config:
    image_id: e17610a2-3ee8-4177-b781-30735aafe1c2
- name: centos-5
  driver_config:
    image_id: 9522c27d-51d9-44ee-8eb3-fb7b14fd4042

suites:
- name: ohai-solo
  run_list:
    - recipe[build-essential]
    - recipe[git::source]
    - recipe[omnibus::default]
    - recipe[omnibus_ohai_solo::default]
    - recipe[omnibus_ohai_solo::upload]
  attributes:
    build_essential:
      compiletime: true
    git:
      version: "1.9.0"
    omnibus:
      ruby_version: "1.9.3-p484"
    omnibus_ohai_solo:
      rs_username: <%= ENV['RS_USERNAME'] %>
      rs_apikey: <%= ENV['RS_APIKEY'] %>
      rs_region: <%= ENV['RS_REGION'] %>
      rs_container: <%= ENV['RS_CONTAINER'] %>
      release_environment: <%= ENV['OHAI_RELEASE_ENV'] %>
      ref: <%= ENV['OHAI_SOLO_VERSION'] || "HEAD" %>
      build_version: <%= ENV['OHAI_SOLO_VERSION'] %>
      append_timestamp: <%= ENV['APPEND_TIMESTAMP'] || "true" %>
    ohai_plugins:
      ref: <%= ENV['OHAI_PLUGINS_VERSION'] || "HEAD" %> 
